# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name when executing supabase init.
project_id = "hubjqllcmbzoojyidgcu"

[functions.ycloud-whatsapp-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false
