# A string used to distinguish different Supabase projects on the same host. Defaults to the working directory name when executing supabase init.
project_id = "hubjqllcmbzoojyidgcu"

[functions.ycloud-whatsapp-webhook]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.ycloud-templates]
enabled = true
verify_jwt = true
import_map = "./functions/ycloud-templates/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ycloud-templates/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ycloud-templates/*.html" ]
